# Generated by Django 5.2.8 on 2025-11-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
