# Generated by Django 5.2.8 on 2025-11-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_customusermodel_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='username',
        ),
    ]
